# Generated by Django 4.1.2 on 2022-10-18 03:17

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='react',
            name='check_out_by',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='react',
            name='date_checked_in',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='react',
            name='date_checked_out',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='react',
            name='location',
            field=models.CharField(blank=True, default='', max_length=256),
        ),
        migrations.AddField(
            model_name='react',
            name='name',
            field=models.CharField(default='', max_length=64),
        ),
        migrations.AlterField(
            model_name='react',
            name='condition',
            field=models.CharField(default='', max_length=256),
        ),
        migrations.AlterField(
            model_name='react',
            name='description',
            field=models.TextField(),
        ),
    ]
