# Generated by Django 4.1.2 on 2022-10-08 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='react',
            name='name',
            field=models.CharField(default='', max_length=64),
        ),
        migrations.AlterField(
            model_name='react',
            name='condition',
            field=models.CharField(default='', max_length=256),
        ),
        migrations.AlterField(
            model_name='react',
            name='description',
            field=models.CharField(default='', max_length=2048),
        ),
    ]
