# Generated by Django 4.1.2 on 2022-10-13 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_react_name_alter_react_condition_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='react',
            name='check_out_by',
            field=models.CharField(blank=True, default='mm/dd/yyyy', max_length=10),
        ),
        migrations.AddField(
            model_name='react',
            name='date_checked_in',
            field=models.CharField(blank=True, default='mm/dd/yyyy', max_length=10),
        ),
        migrations.AddField(
            model_name='react',
            name='date_checked_out',
            field=models.CharField(blank=True, default='mm/dd/yyyy', max_length=10),
        ),
        migrations.AddField(
            model_name='react',
            name='location',
            field=models.CharField(blank=True, default='', max_length=256),
        ),
    ]
