# Generated by Django 4.1.2 on 2022-10-15 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_react_check_out_by_react_date_checked_in_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='react',
            name='check_out_by',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='react',
            name='date_checked_in',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='react',
            name='date_checked_out',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='react',
            name='description',
            field=models.TextField(),
        ),
    ]
