# Generated by Django 4.1.2 on 2022-10-15 18:11

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_react_check_out_by_alter_react_date_checked_in_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='react',
            name='check_out_by',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='react',
            name='date_checked_in',
            field=models.DateField(default=datetime.date(2022, 10, 15)),
        ),
        migrations.AlterField(
            model_name='react',
            name='date_checked_out',
            field=models.DateField(),
        ),
    ]
