# Generated by Django 4.1.2 on 2022-10-15 18:12

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_react_check_out_by_alter_react_date_checked_in_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='react',
            name='date_checked_in',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
